# Generated by Django 4.2.5 on 2024-06-18 05:25

from django.db import migrations, models
import website.validators


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='odd_filed',
            field=models.IntegerField(default=1, validators=[website.validators.odd_number_validate]),
            preserve_default=False,
        ),
    ]
